name: Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'
      - 'server/**'

  pull_request:
    branches:
      - main
    paths:
      - 'infra/**'
      - 'server/**'

  workflow_dispatch:

env:
  DOTNET_VERSION: '9.0.x'
  SERVER_PROJECT_PATH: server/WeightTracker.Api/WeightTracker.Api.csproj

jobs:
  build-infrastructure:
    name: Build Bicep Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate Bicep
        run: |
          cd infra/azure
          az bicep install
          az bicep build -f main.bicep
          # az bicep build-params -f main.bicepparam

      - name: Upload Infrastructure Artifact
        uses: actions/upload-artifact@v4
        with:
          name: infra
          path: infra/azure/*.json
          if-no-files-found: error

  build-server:
    name: Build Server Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ${{ env.SERVER_PROJECT_PATH }} --no-build --configuration Release --output webapp

      - name: Upload Server Artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: webapp/**
          if-no-files-found: error

  deploy-infrastructure:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    needs: [build-infrastructure, build-server]
    environment: prod
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download Infrastructure Artifact
        uses: actions/download-artifact@v4
        with:
          name: infra
          path: infra

      - name: Deploy Infrastructure
        run: |
          az deployment group create \
            --resource-group ${{ vars.RESOURCE_GROUP_NAME }} \
            --template-file infra/main.json \
            --parameters infra/parameters.json

  deploy-server:
    name: Deploy Server
    runs-on: ubuntu-latest
    needs: [deploy-infrastructure, build-server]
    environment: prod
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download Server Artifact
        uses: actions/download-artifact@v4
        with:
          name: webapp
          path: webapp

      - name: Deploy Server App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ vars.APP_NAME }}
          package: webapp
